name: anymex
description: "AnymeX - One Stop for anime, manga, novels"
publish_to: "none"
version: 2.8.5-alpha

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  crystal_navigation_bar: ^1.0.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  iconly: ^1.0.1
  iconsax: ^0.0.8
  text_scroll: ^0.2.0
  better_player: ^0.0.84
  custom_sliding_segmented_control: ^1.8.3
  provider: ^6.1.2
  cached_network_image: ^3.4.1
  animated_segmented_tab_control: ^2.0.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  smooth_page_indicator: ^1.2.0+3
  wakelock_plus: ^1.2.8
  dynamic_color: ^1.7.0
  device_info_plus: ^10.1.2
  shimmer: ^3.0.0
  url_launcher: ^6.3.0
  crypto: ^3.0.5
  flutter_dotenv: ^5.1.0
  iconify_flutter: ^0.0.5
  html: any
  transformable_list_view: ^0.6.0
  encrypt: ^5.0.3
  hugeicons: ^0.0.7
  google_fonts: ^6.2.1
  pointycastle: ^3.9.1
  dio: ^5.7.0
  permission_handler: ^11.3.1
  flutter_local_notifications: ^18.0.1
  flutter_web_auth_2: ^4.0.2
  media_kit: ^1.1.10+1
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  window_manager: ^0.4.3
  http_interceptor: ^2.0.0
  js_packer: ^0.0.5
  xpath_selector_html_parser: ^3.0.1
  dart_eval: ^0.7.10
  flutter_qjs:
    git:
      url: https://github.com/kodjodevf/flutter_qjs.git
      ref: main
  json_annotation: ^4.9.0
  isar: ^3.1.0+1
  json_path: ^0.7.4
  intl: ^0.20.1
  isar_flutter_libs: 3.1.0+1
  riverpod_annotation: ^2.6.1
  pseudom: ^1.0.1
  flutter_rust_bridge: ^2.7.0
  freezed_annotation: ^2.4.4
  flutter_riverpod: ^2.6.1
  grouped_list: ^6.0.0
  volume_controller: ^2.0.8
  screen_brightness: ^0.2.2+1
  expandable_page_view: ^1.0.17
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  rename_app: ^1.6.1
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_transparent.png
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf

    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
