blank_issues_enabled: false
contact_links:
  - name: 🧑‍💻 AnymeX Help on Discord
    url: https://discord.com/invite/azAMuBWd8C
    about: Get support, ask questions, and join the community discussions.

  - name: 📱 AnymeX Help on Telegram
    url: https://t.me/AnymeX_Discussion
    about: Connect with the community, ask questions, and get help directly on Telegram.
