name: Bug Report Greeting
on:
  issues:
    types: [opened]
jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Check if the issue is labeled as a Bug Report
      id: check_bug_label
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ISSUE_NUMBER=$(jq -r '.issue.number' "$GITHUB_EVENT_PATH")
        LABELS=$(gh issue view $ISSUE_NUMBER --json labels --jq '.labels[].name')
        if echo "$LABELS" | grep -q 'bug'; then
          echo "skip_label_check=false" >> $GITHUB_ENV
        else
          echo "skip_label_check=true" >> $GITHUB_ENV
        fi
    - name: Check if the issue creator is the repo owner
      if: env.skip_label_check == 'false'
      id: check_owner
      run: |
        ISSUE_AUTHOR=$(jq -r '.issue.user.login' "$GITHUB_EVENT_PATH")
        REPO_OWNER=$(jq -r '.repository.owner.login' "$GITHUB_EVENT_PATH")
        if [ "$ISSUE_AUTHOR" = "$REPO_OWNER" ]; then
          echo "skip=true" >> $GITHUB_ENV
        else
          echo "skip=false" >> $GITHUB_ENV
        fi
    - name: Check if the user has submitted a bug report before
      if: env.skip == 'false'
      id: check_first_bug_report
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ISSUE_AUTHOR=$(jq -r '.issue.user.login' "$GITHUB_EVENT_PATH")
        ISSUE_NUMBER=$(jq -r '.issue.number' "$GITHUB_EVENT_PATH")
        PREVIOUS_REPORTS=$(gh issue list --author "$ISSUE_AUTHOR" --label "Bug" --state all --json number --jq '. | map(select(.number != '$ISSUE_NUMBER')) | length')
        if [ "$PREVIOUS_REPORTS" -eq 0 ]; then
          echo "skip_first_report=false" >> $GITHUB_ENV
        else
          echo "skip_first_report=true" >> $GITHUB_ENV
        fi
    - name: Check for Extension Checkbox
      if: env.skip_label_check == 'false' && env.skip != 'true' && env.skip_first_report != 'true'
      uses: actions/github-script@v6
      with:
        script: |
          const issueBody = context.payload.issue.body || '';
          const extensionCheckboxPattern = /- \[[xX]\]\s*If this is an issue with an extension, I should be opening an issue in the extension's repository\./;
          if (extensionCheckboxPattern.test(issueBody)) {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              body: "If this is an issue with an extension, please open an issue in the extension's repository."
            });
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              state: "closed",
              state_reason: "not_planned"
            });
          } else {
            const issueNumber = context.payload.issue.number;
            const message = `
            **🛠️ Thank you for reporting a bug!**  
            Your issue has been successfully submitted and is now awaiting review. We appreciate your help in making AnymeX better.
            **🔍 What Happens Next**  
            - Our team will investigate the issue and provide updates as soon as possible.  
            - You may be asked for additional details or clarification if needed.  
            - Once resolved, we'll notify you of the fix or provide a workaround.
            **👥 Connect with Us**  
            - **[Discord](https://discord.com/invite/azAMuBWd8C)**: Engage with our community and ask questions.  
            - **[Telegram](https://t.me/AnymeX_Discussion)**: Reach out for real-time discussions and updates.
            We're working hard to resolve the issue and appreciate your patience!
            `;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: message
            });
          }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
