name: Build and Release AnymeX

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-mobile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [android, ios]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.3"

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Android with Split ABI
        if: matrix.platform == 'android'
        run: |
          flutter build apk --split-per-abi

      - name: Rename and Upload APKs (Split ABI)
        if: matrix.platform == 'android'
        run: |
          mv build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk build/app/outputs/flutter-apk/app-armeabi-v7a-release-split.apk
          mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk build/app/outputs/flutter-apk/app-arm64-v8a-release-split.apk
          mv build/app/outputs/flutter-apk/app-x86_64-release.apk build/app/outputs/flutter-apk/app-x86_64-release-split.apk

      - name: Build Universal APK
        if: matrix.platform == 'android'
        run: |
          flutter build apk --release

      - name: Rename and Upload Universal APK
        if: matrix.platform == 'android'
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/app-release-universal.apk

      - name: Build iOS (macOS only)
        if: matrix.platform == 'ios'
        runs-on: macos-latest
        run: |
          flutter build ios --release --no-codesign

      - name: Upload Artifact (Mobile)
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}-build
          path: |
            build/app/outputs/flutter-apk/*.apk
            build/ios/iphoneos/*.app

  build-desktop:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.3"

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Desktop
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            flutter build linux --release
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            flutter build macos --release
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            flutter build windows --release
          fi

      - name: Zip Windows Release
        if: matrix.os == 'windows-latest'
        run: |
          cd build\windows\x64\runner\Release
          powershell Compress-Archive -Path * -DestinationPath AnymeX_Windows.zip

      - name: Upload Artifact (Desktop)
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-build
          path: |
            build/*/outputs/*
            build/windows/x64/runner/Release/AnymeX_Windows.zip

  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Latest Non-Pre-Release Tag
        id: get_tag
        run: |
          LATEST_TAG=$(git tag --list | grep -vE "beta|alpha" | sort -V | tail -n 1)
          echo "Latest non-pre-release tag: $LATEST_TAG"
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Generate Changelog
        id: changelog
        run: |
          COMMITS=$(git log $LATEST_TAG..HEAD --pretty=format:"%H %s" --decorate --no-abbrev-commit)

          CHANGELOG=""
          while IFS= read -r line; do
            HASH=$(echo "$line" | awk '{print $1}')
            MESSAGE=$(echo "$line" | cut -d' ' -f2-)
            CHANGELOG="$CHANGELOG$REPO_URL$HASH $MESSAGE\n"
          done <<< "$COMMITS"

          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
          echo "CHANGELOG=$CHANGELOG" >> $GITHUB_ENV

      - name: Create Snapshot Release
        uses: softprops/action-gh-release@v2
        with:
          repository: RyanYuuki/AnymeX
          make_latest: true
          draft: false
          tag_name: v${{ github.run_number }}  
          body: |
            ${{ env.CHANGELOG }}
          files: |
            build_final/*
            build/windows/x64/runner/Release/AnymeX_Windows.zip
          token: ${{ secrets.SNAPSHOTS_REPO_SECRET }}

      - name: Upload all APKs
        uses: actions/upload-artifact@v3
        with:
          name: all-apks
          path: build_final/**

