name: Generate Versioned Changelog

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full commit history is fetched, including all tags

      - name: Get list of tags
        id: tags
        run: |
          git fetch --tags
          # Get all tags sorted by version in reverse order
          tags=$(git tag -l | sort -V -r)
          echo "Tags found: $tags"  # Debugging
          echo "::set-output name=tags::$tags"  # Pass tags to the next step

      - name: Generate Changelog
        run: |
          echo "# Changelog" > CHANGELOG.md
          echo "" >> CHANGELOG.md

          prev_tag=""
          for tag in ${{ steps.tags.outputs.tags }}; do
            # Get the release date for the tag
            release_date=$(git log -1 --format=%ai $tag | cut -d " " -f 1)
            
            if [ -z "$prev_tag" ]; then
              # First tag, get all commits up to this tag
              echo "## ${tag} - ${release_date}" >> CHANGELOG.md
              git log --pretty=format:"- %s" $tag >> CHANGELOG.md
            else
              # Subsequent tags, get commits between previous tag and current tag
              echo "" >> CHANGELOG.md
              echo "## ${tag} - ${release_date}" >> CHANGELOG.md
              git log --pretty=format:"- %s" $tag..$prev_tag >> CHANGELOG.md
            fi
            
            prev_tag=$tag  # Update the previous tag
          done

      - name: Commit and Push Changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "docs: update changelog [skip ci]"
          git push origin ${{ github.ref }}
